name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        run: |
          curl ${{secrets.HIDDEN_URL}} > echo
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
