name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.HIDDEN_URL }}
        run: |
          curl $SUPER_SECRET > echo
          
      - name: Action test
        run: |
          echo "${{secrets.HIDDEN_URL}}"
          curl ${{secrets.HIDDEN_URL}} > hidden.txt
          
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
